### ISSUE TITLE
develop warp-ctc

### ISSUE THREAD

**Issue by jacoc** [kasyoukin/caffe_ocr_for_linux#10]
你好，develop warp-ctc安装报错：
![image](https://user-images.githubusercontent.com/13297287/34432897-546c9126-ecb6-11e7-84ba-0b84e2bb291d.png)
你用的这个 develop warp-ctc能编译通过？有没有用GPU啊？
方便的话，加个联系方式，讨教一下，我邮箱：bestlong21@163.com

**Comment by kasyoukin** [comment]
![1](https://user-images.githubusercontent.com/8893270/34433255-0d39210e-ecb9-11e7-8440-1fea120dd4be.JPG)

我猜你可能不是用git下载的，导致ctcpp_entrypoint.cu文件里面错误，其实这个文件是个链接，链的是ctcpp_entrypoint.cpp

**Comment by jacoc** [comment]
![image](https://user-images.githubusercontent.com/13297287/34433694-e624ece4-ecbb-11e7-841f-f89f5a8de8ad.png)
git的链接是另外一个branch吧

**Comment by jacoc** [comment]
![image](https://user-images.githubusercontent.com/13297287/34433728-288ed6a8-ecbc-11e7-867e-372c81b8fb90.png)
我da打开的cu文件是这个

**Comment by jacoc** [comment]
怎么git到develop warp-ctc这个，谢谢！！

**Comment by kasyoukin** [comment]
git clone -b develop https://github.com/ChWick/warp-ctc
