### ISSUE TITLE
undefined reference to `compute_ctc_loss'

### ISSUE THREAD

**Issue by AlphaToad** [kasyoukin/caffe_ocr_for_linux#14]
您好，我进行编译的时候出现了如下错误：
build_release/lib/libcaffe.so: undefined reference to `ctcStatus_t CTC::get_workspace_size<float>(int const*, int const*, int, int, ctcOptions, unsigned long*)'
.build_release/lib/libcaffe.so: undefined reference to `compute_ctc_loss'
.build_release/lib/libcaffe.so: undefined reference to `ctcStatus_t CTC::compute_ctc_loss<double>(double const*, double*, int const*, int const*, int const*, int, int, double*, void*, ctcOptions)'
.build_release/lib/libcaffe.so: undefined reference to `ctcStatus_t CTC::get_workspace_size<double>(int const*, int const*, int, int, ctcOptions, unsigned long*)'
.build_release/lib/libcaffe.so: undefined reference to `ctcGetStatusString'
collect2: error: ld returned 1 exit status
这个是否由于我的warp-ctc没有装好？我将warp-ctc编译完之后，除了修改makefile.config的路径之外，还有将ctcpp.h以及libwarpctc.so拷贝到/usr/lib下，是否还有其他遗漏步骤？
万分感谢！

**Comment by AlphaToad** [comment]
问题已解决，是warp-ctc编译的问题

**Comment by kobean** [comment]
我也遇到了同样的问题，请问warp-ctc编译哪里出了问题，您是怎么解决的？
