### ISSUE TITLE
ocr_test result is wrong

### ISSUE THREAD

**Issue by zyxrrr** [kasyoukin/caffe_ocr_for_linux#16]
Hello, my result is
经/6]../../examples/ocr/20436328_800384098.jpg[cost:109 ms]: 姻
洲/6]../../examples/ocr/20437703_937698549.jpg[cost:104 ms]: 业
风/6]../../examples/ocr/20436765_2556130357.jpg[cost:104 ms]: 3
持/6]../../examples/ocr/20440484_2127180630.jpg[cost:104 ms]: ?
人/6]../../examples/ocr/20436312_1683447152.jpg[cost:135 ms]: 美
，/6]../../examples/ocr/20438234_4066860539.jpg[cost:109 ms]: 究
I use CPU_ONLY mode,and resnet-res-blstm\inception-bn-res-blstm are all wrong like this.

**Comment by zyxrrr** [comment]
已解决，都怪自己没看清！
需要两步把label.txt进行转换
iconv -f GBK -t UTF-8 label.txt > mylabel.txt
dos2unix mylabel.txt
最后再把mylabel.txt改成label.txt

**Comment by zhangtao22** [comment]
你转换的时候有没有遇到
inception-bn-res-blstm$ iconv -f GBK -t UTF-8 label.txt > mylabel.txt
iconv: illegal input sequence at position 16333
你应该也是下的http://pan.baidu.com/s/1i5d5zdN里面的模型吧
