### ISSUE TITLE
/convert_mnist_siamese_data.cpp:96:24: error

### ISSUE THREAD

**Issue by zhangtao22** [kasyoukin/caffe_ocr_for_linux#17]
examples/siamese/convert_mnist_siamese_data.cpp:96:24: error: no matching function for call to ‘caffe::Datum::set_label(int)’
       datum.set_label(1);
                        ^
In file included from examples/siamese/convert_mnist_siamese_data.cpp:15:0:
.build_release/src/caffe/proto/caffe.pb.h:11901:13: note: candidate: void caffe::Datum::set_label(int, google::protobuf::int32)
 inline void Datum::set_label(int index, ::google::protobuf::int32 value) {
             ^
.build_release/src/caffe/proto/caffe.pb.h:11901:13: note:   candidate expects 2 arguments, 1 provided
examples/siamese/convert_mnist_siamese_data.cpp:98:24: error: no matching function for call to ‘caffe::Datum::set_label(int)’
       datum.set_label(0);
                        ^
In file included from examples/siamese/convert_mnist_siamese_data.cpp:15:0:
.build_release/src/caffe/proto/caffe.pb.h:11901:13: note: candidate: void caffe::Datum::set_label(int, google::protobuf::int32)
 inline void Datum::set_label(int index, ::google::protobuf::int32 value) {
             ^
.build_release/src/caffe/proto/caffe.pb.h:11901:13: note:   candidate expects 2 arguments, 1 provided
Makefile:588: recipe for target '.build_release/examples/siamese/convert_mnist_siamese_data.o' failed
make: *** [.build_release/examples/siamese/convert_mnist_siamese_data.o] Error 1
大家有没有遇到这个问题，谢谢

**Comment by xap1992** [comment]
我遇到了，我估计是修改多标签输入导致的。我将关于mnist相关的cpp文件全部删除后，就能编译了

**Comment by zhangtao22** [comment]
@xap1992 谢谢 我也是删了

**Comment by xap1992** [comment]
你有没有尝试训练自己的数据？我训练自己的数据时，返现loss降的非常快，但是测试准确度非常低，哪怕是使用训练集去测试。

**Comment by kasyoukin** [comment]
我训练过自己的数据，效果还不错的。你可以检查下你的数据是不是有问题，训练时是否开启shuffle，另外loss降下去了也要多训练些时间的，多跑几个epoch再试试

**Comment by xap1992** [comment]
大神能否提供下自己训练样本，label文件，训练网络，以及训练好的文件，供参考下。在此感谢大神的无私奉献

**Comment by zyxrrr** [comment]
@kasyoukin 
你好！训练样本是不是就是生成的图片，每个样本固定10个字符，图片分辨率统一为280x32 ？
目前应该不支持变长的标签吧。并且目前最新的caffe的LSTM已经支持了这种样本吧。

**Comment by ghost** [comment]
@kasyoukin   您好，您是怎么创建自己的训练数据的，报错LMBD格式不对
