### ISSUE TITLE
▒▒/1]/home/zhangtao/work/caffe_ocr_for_linux/data/img/20438234_4066860539.jpg[cost:20.3835 ms]: ▒▒

### ISSUE THREAD

**Issue by zhangtao22** [kasyoukin/caffe_ocr_for_linux#18]
我用inception-bn-res-blstm chi 测试出来是这
转码报错
zhangtao@BoHong:~/work/caffe_ocr_for_linux/models/inception-bn-res-blstm$ iconv -f GBK -t UTF-8 label.txt > mylabel.txt
iconv: illegal input sequence at position 16333
zhangtao@BoHong:~/work/caffe_ocr_for_linux/models/inception-bn-res-blstm$ iconv -f ANSI -t UTF-8 label.txt > mylabel.txt
iconv: conversion from `ANSI' is not supported
Try `iconv --help' or `iconv --usage' for more information.

**Comment by zhangtao22** [comment]
问题已解决

**Comment by saintscript** [comment]
怎么解决的啊
