### ISSUE TITLE
关于caffe make时的错误

### ISSUE THREAD

**Issue by teresasun521** [kasyoukin/caffe_ocr_for_linux#19]
你好，我的环境是 ubuntu14.04  cudn7.5 ，cudnn5.1
protobuf2.6.1
在编译过程中出现如下错误，怎么回事呢？能帮我看看问题吗？
我初次接触caffe，安装过程中解决问题比较没经验，麻烦耐心帮我解答一下，谢谢

**Comment by teresasun521** [comment]
Linking CXX static library ../../lib/libcaffeproto.a
[  1%] Built target caffeproto
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adadelta_solver.cu.o
In file included from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/util/cudnn.hpp:8:0,
                 from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/util/device_alternate.hpp:40,
                 from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/common.hpp:19,
                 from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/util/math_functions.hpp:9,
                 from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/src/caffe/solvers/adadelta_solver.cu:1:
/home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/util/cudnn.hpp:8:0,
                 from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/util/device_alternate.hpp:40,
                 from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/common.hpp:19,
                 from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/util/math_functions.hpp:9,
                 from /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/src/caffe/solvers/adadelta_solver.cu:1:
/home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/include/caffe/proto/caffe.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
 #include <google/protobuf/arena.h>
                                   ^
compilation terminated.
CMake Error at cuda_compile_generated_adadelta_solver.cu.o.cmake:206 (message):
  Error generating
  /home/sunyf/caffe_ocr/caffe_ocr_for_linux-master/build/src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adadelta_solver.cu.o


make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_adadelta_solver.cu.o] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by vincezengqiang** [comment]
hey，最后你编译成功了吗?使用的protobuf版本是多少呢？
