### ISSUE TITLE
ocr_test.cpp编译问题

### ISSUE THREAD

**Issue by cos120** [kasyoukin/caffe_ocr_for_linux#2]
感谢分享！

在编译caffe的过程中遇到这个问题

ctc.h和ctcpp.h在　/usr/local/include路径中

Makefile.config
```makefile
INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include
```

编译错误信息
```
ocr_test.cpp:(.text+0x265)：对‘ctcStatus_t CTC::get_workspace_size<float>(int const*, int const*, int, int, ctcOptions, unsigned long*)’未定义的引用
ocr_test.cpp:(.text+0x44f)：对‘ctcStatus_t CTC::compute_ctc_loss<float>(float const*, float*, int const*, int const*, int const*, int, int, float*, void*, ctcOptions)’未定义的引用

```
不知道哪里错了，寻求一下您的帮助，谢谢．

**Comment by kasyoukin** [comment]
warp-ctc编译后的so文件，应该不在你的lib路径中，加进去就好了，或者你把so文件copy到/usr/lib目录下

**Comment by cos120** [comment]
按照您的说法我把`libwarpctc.so` 拷贝到`/usr/lib`下还是编译不过

您readme里面warp-ctc的安装方法是编译之后把so和h文件拷贝到`/usr/lib`和`/usr/local/include`中就可以吗?

**Comment by kasyoukin** [comment]
你的Makefile文件和我的是一样的吗

**Comment by cos120** [comment]
谢谢您的回复!

我的环境和您测试的环境有些不同,我是ubuntu14.04,cuda7.5的.
最后通过修改`build/tools/CMakeFiles/ocr_test.dir/link.txt`把ctc的库连接上了.

**Comment by kasyoukin** [comment]
好的
