### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by gllspeed** [kasyoukin/caffe_ocr_for_linux#44]
你好，编译必须要用到opencv吗，报以下错误

AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lopencv_imgcodecs
collect2: error: ld returned 1 exit status
Makefile:581: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

**Comment by kasyoukin** [comment]
缺啥就自己装下吧
sudo apt-get install libopencv-highgui2.4v5  libopencv-imgproc2.4v5

**Comment by gllspeed** [comment]
好的，谢谢
