### ISSUE TITLE
ocr_test.c 引用了ICNNPredict，请问它定义的函数代码在哪可以找到？

### ISSUE THREAD

**Issue by Xiao-OMG** [kasyoukin/caffe_ocr_for_linux#6]
你好，其实想找到这个函数的详细代码，CreatePredictInstance（）
方便的话帮个忙，谢谢哈~

**Comment by kasyoukin** [comment]
这个你搜一下就能找到了吧

**Comment by funfunfountain** [comment]
我也没有找到

**Comment by Xiao-OMG** [comment]
自己写一个吧，参考imagenet那个classification cpp

**Comment by kasyoukin** [comment]
![2018-01-11 10-36-00](https://user-images.githubusercontent.com/8893270/34805953-7150ee0e-f6bb-11e7-983f-6a06d64aea5d.png)
