### ISSUE TITLE
error: cannot convert ‘const double* const’ to ‘const float*’ 

### ISSUE THREAD

**Issue by cszhz** [kasyoukin/caffe_ocr_for_linux#8]
Could you help on this issue when I execute make command. thx a lot

CXX src/caffe/layers/tanh_layer.cpp
CXX src/caffe/layers/threshold_layer.cpp
CXX src/caffe/layers/tile_layer.cpp
CXX src/caffe/layers/transpose_layer.cpp
CXX src/caffe/layers/warp_ctc_loss_layer.cpp
src/caffe/layers/warp_ctc_loss_layer.cpp: In instantiation of ‘void caffe::WarpCTCLossLayer<Dtype>::Forward_cpu(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = double]’:
src/caffe/layers/warp_ctc_loss_layer.cpp:276:1:   required from here
src/caffe/layers/warp_ctc_loss_layer.cpp:158:31: error: cannot convert ‘const double* const’ to ‘const float*’ for argument ‘1’ to ‘ctcStatus_t compute_ctc_loss(const float*, float*, const int*, const int*, const int*, int, int, float*, void*, ctcOptions)’
                               );

**Comment by kasyoukin** [comment]
the problem maybe is  warp-ctc,you could install the dev branch
